spring:
  application:
    name: eshop

  docker:
    compose:
      file: monolith/compose.yaml

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true