apiVersion: v1
kind: Service
metadata:
  name: shipping-postgres-db
  namespace: microservices
spec:
  selector:
    app: shipping-postgres-db
  ports:
    - port: 5434
      targetPort: 5432
  type: ClusterIP