server:
  port: 8083

spring:
  application:
    name: notification

  docker:
    compose:
      file: microservices/notification/compose.yaml

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      order-created: orderCreatedTopic
      shipment-created: shipmentCreatedTopic
    consumer:
      group-id: notification-service
    backoff:
      interval: 1000
      max-attempts: 3

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

