server:
  port: 8083

spring:
  application:
    name: notification

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      order-created: orderCreatedTopic
      shipment-created: shipmentCreatedTopic
    consumer:
      group-id: notification-service
    backoff:
      interval: 1000
      max-attempts: 3