kind: Service
apiVersion: v1
metadata:
  name: shipping-application
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: shipping-application
  ports:
    - port: 8082
      targetPort: 8082
