kind: Service
apiVersion: v1
metadata:
  name: notification-application
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: notification-application
  ports:
    - port: 8080
      targetPort: 8080
