kind: Service
apiVersion: v1
metadata:
  name: notification-application
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: notification-application
  ports:
    - port: 8083
      targetPort: 8083
