apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-postgres-db-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi