apiVersion: v1
kind: Service
metadata:
  name: notification-postgres-db
  namespace: microservices
spec:
  selector:
    app: notification-postgres-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP