kind: Service
apiVersion: v1
metadata:
  name: ordering-application
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: ordering-application
  ports:
    - port: 8080
      targetPort: 8080
