kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: microservices
  name: ordering-ms-pod-killer
spec:
  schedule: '*/20 * * * * *'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - microservices
      labelSelectors:
        app: ordering-application
    mode: fixed
    value: '1'
    action: pod-kill
    gracePeriod: 1
